const wordPairs = [
    { majority: 'Carro', infiltrator: 'Moto', category: 'Veículo' },
    { majority: 'Moto', infiltrator: 'Carro', category: 'Veículo' },
    { majority: 'Futebol', infiltrator: 'Basquete', category: 'Esporte' },
    { majority: 'Basquete', infiltrator: 'Futebol', category: 'Esporte' },
    { majority: 'Praia', infiltrator: 'Piscina', category: 'Lugar' },
    { majority: 'Piscina', infiltrator: 'Praia', category: 'Lugar' },
    { majority: 'Cachorro', infiltrator: 'Gato', category: 'Animal' },
    { majority: 'Gato', infiltrator: 'Cachorro', category: 'Animal' },
    { majority: 'Filme', infiltrator: 'Série', category: 'Entretenimento' },
    { majority: 'Série', infiltrator: 'Filme', category: 'Entretenimento' },
    { majority: 'Pizza', infiltrator: 'Hambúrguer', category: 'Comida' },
    { majority: 'Hambúrguer', infiltrator: 'Pizza', category: 'Comida' },
    { majority: 'Sol', infiltrator: 'Lua', category: 'Astro' },
    { majority: 'Lua', infiltrator: 'Sol', category: 'Astro' },
    { majority: 'Computador', infiltrator: 'Celular', category: 'Tecnologia' },
    { majority: 'Celular', infiltrator: 'Computador', category: 'Tecnologia' },
    { majority: 'Violão', infiltrator: 'Guitarra', category: 'Instrumento Musical' },
    { majority: 'Guitarra', infiltrator: 'Violão', category: 'Instrumento Musical' },
    { majority: 'Café', infiltrator: 'Chá', category: 'Bebida' },
    { majority: 'Chá', infiltrator: 'Café', category: 'Bebida' },
    { majority: 'Verão', infiltrator: 'Inverno', category: 'Estação do Ano' },
    { majority: 'Inverno', infiltrator: 'Verão', category: 'Estação do Ano' },
    { majority: 'Brasil', infiltrator: 'Argentina', category: 'País' },
    { majority: 'Argentina', infiltrator: 'Brasil', category: 'País' },
    { majority: 'Médico', infiltrator: 'Enfermeiro', category: 'Profissão' },
    { majority: 'Enfermeiro', infiltrator: 'Médico', category: 'Profissão' },
    { majority: 'Livro', infiltrator: 'Revista', category: 'Leitura' },
    { majority: 'Revista', infiltrator: 'Livro', category: 'Leitura' },
    { majority: 'Casa', infiltrator: 'Apartamento', category: 'Moradia' },
    { majority: 'Apartamento', infiltrator: 'Casa', category: 'Moradia' },
    { majority: 'Rio', infiltrator: 'Mar', category: 'Geografia' },
    { majority: 'Mar', infiltrator: 'Rio', category: 'Geografia' },
    { majority: 'Pintura', infiltrator: 'Desenho', category: 'Arte' },
    { majority: 'Desenho', infiltrator: 'Pintura', category: 'Arte' },
    { majority: 'Ouro', infiltrator: 'Prata', category: 'Metal' },
    { majority: 'Prata', infiltrator: 'Ouro', category: 'Metal' },
    { majority: 'Garfo', infiltrator: 'Colher', category: 'Utensílio' },
    { majority: 'Colher', infiltrator: 'Garfo', category: 'Utensílio' },
    { majority: 'Cama', infiltrator: 'Sofá', category: 'Móvel' },
    { majority: 'Sofá', infiltrator: 'Cama', category: 'Móvel' },
    { majority: 'Corrida', infiltrator: 'Caminhada', category: 'Esporte' },
    { majority: 'Caminhada', infiltrator: 'Corrida', category: 'Esporte' },
    { majority: 'Laranja', infiltrator: 'Limão', category: 'Comida' },
    { majority: 'Limão', infiltrator: 'Laranja', category: 'Comida' },
    { majority: 'Tubarão', infiltrator: 'Golfinho', category: 'Animal' },
    { majority: 'Golfinho', infiltrator: 'Tubarão', category: 'Animal' },
    { majority: 'Helicóptero', infiltrator: 'Avião', category: 'Veículo' },
    { majority: 'Avião', infiltrator: 'Helicóptero', category: 'Veículo' },
    { majority: 'Teatro', infiltrator: 'Cinema', category: 'Entretenimento' },
    { majority: 'Cinema', infiltrator: 'Teatro', category: 'Entretenimento' },
    { majority: 'Rádio', infiltrator: 'Televisão', category: 'Tecnologia' },
    { majority: 'Televisão', infiltrator: 'Rádio', category: 'Tecnologia' },
    { majority: 'Bateria', infiltrator: 'Piano', category: 'Instrumento Musical' },
    { majority: 'Piano', infiltrator: 'Bateria', category: 'Instrumento Musical' },
    { majority: 'Vinho', infiltrator: 'Cerveja', category: 'Bebida' },
    { majority: 'Cerveja', infiltrator: 'Vinho', category: 'Bebida' },
    { majority: 'Primavera', infiltrator: 'Outono', category: 'Estação do Ano' },
    { majority: 'Outono', infiltrator: 'Primavera', category: 'Estação do Ano' },
    { majority: 'Japão', infiltrator: 'China', category: 'País' },
    { majority: 'China', infiltrator: 'Japão', category: 'País' },
    { majority: 'Advogado', infiltrator: 'Juiz', category: 'Profissão' },
    { majority: 'Juiz', infiltrator: 'Advogado', category: 'Profissão' },
    { majority: 'Jornal', infiltrator: 'Blog', category: 'Leitura' },
    { majority: 'Blog', infiltrator: 'Jornal', category: 'Leitura' },
    { majority: 'Hotel', infiltrator: 'Pousada', category: 'Lugar' },
    { majority: 'Pousada', infiltrator: 'Hotel', category: 'Lugar' },
    { majority: 'Montanha', infiltrator: 'Vale', category: 'Geografia' },
    { majority: 'Vale', infiltrator: 'Montanha', category: 'Geografia' },
    { majority: 'Escultura', infiltrator: 'Fotografia', category: 'Arte' },
    { majority: 'Fotografia', infiltrator: 'Escultura', category: 'Arte' },
    { majority: 'Cobre', infiltrator: 'Bronze', category: 'Metal' },
    { majority: 'Bronze', infiltrator: 'Cobre', category: 'Metal' },
    { majority: 'Faca', infiltrator: 'Tesoura', category: 'Utensílio' },
    { majority: 'Tesoura', infiltrator: 'Faca', category: 'Utensílio' },
    { majority: 'Mesa', infiltrator: 'Cadeira', category: 'Móvel' },
    { majority: 'Cadeira', infiltrator: 'Mesa', category: 'Móvel' }
];

const boboWords = [
    { word: 'Foguete', category: 'Espacial' },
    { word: 'Dragão', category: 'Fantasia' },
    { word: 'Unicórnio', category: 'Fantasia' },
    { word: 'Pudim', category: 'Sobremesa' },
    { word: 'Meia', category: 'Vestuário' },
    { word: 'Lâmpada', category: 'Objeto' },
    { word: 'Nuvem', category: 'Natureza' },
    { word: 'Tapete', category: 'Decoração' },
    { word: 'Guarda-chuva', category: 'Acessório' },
    { word: 'Chave', category: 'Objeto' },
    { word: 'Fantasma', category: 'Sobrenatural' },
    { word: 'Pirâmide', category: 'Construção' },
    { word: 'Vulcão', category: 'Natureza' },
    { word: 'Robô', category: 'Ficção Científica' },
    { word: 'Sombra', category: 'Conceito' },
    { word: 'Eco', category: 'Conceito' },
    { word: 'Arco-íris', category: 'Natureza' },
    { word: 'Castelo', category: 'Construção' },
    { word: 'Bússola', category: 'Objeto' },
    { word: 'Telescópio', category: 'Objeto' }
];

const rules = {
    bobo: { title: 'O Bobo', description: 'Recebe uma palavra aleatória. Seu objetivo é ser eliminado. Se conseguir, vence sozinho!' },
    cumplice: { title: 'O Cúmplice', description: 'Aliado do Infiltrado, recebe a mesma palavra e vence junto com ele. O Infiltrado não sabe quem é o Cúmplice.' },
    anjo: { title: 'Anjo da Guarda', description: 'A cada rodada, escolhe secretamente um jogador para proteger. Se o jogador protegido for o mais votado, a eliminação é cancelada. O Anjo não pode proteger a mesma pessoa duas vezes seguidas.' },
    detetive: { title: 'O Detetive', description: 'A cada rodada, investiga secretamente um jogador. No modo "Rápido", o resultado sai na hora. No modo "Lento", o resultado chega apenas na rodada seguinte.' },
    vidente: { title: 'O Vidente', description: 'A cada rodada, tem uma pequena chance de descobrir secretamente o nome de outro jogador que também está do lado da Maioria.'},
    coveiro: { title: 'O Coveiro', description: 'A cada rodada, após uma eliminação, ele descobre secretamente o papel (mas não a palavra) do jogador que foi eliminado.'},
    agenteDuplo: { title: 'O Agente Duplo', description: 'Começa como Maioria. O Infiltrado, uma vez por jogo, pode escolher "ativá-lo" secretamente durante a fase de ação. A partir daí, o Agente Duplo se torna um Cúmplice e vence com o Infiltrado.'},
    mimico: { title: 'O Mímico', description: 'Não recebe palavra. Na primeira noite, ele vê quem é o Infiltrado. Ele não pode falar durante o jogo, ajudando a Maioria apenas com gestos e votos.'},
    eventos: { title: 'Eventos Aleatórios', description: 'Se ativado, um evento surpresa pode acontecer após uma eliminação, mudando as regras da próxima rodada.' },
    'random-mode': { title: 'Modo Aleatório', description: 'Ativa uma seleção aleatória de papéis especiais a cada partida, dependendo do número de jogadores. Surpresa total!'}
};
